version: "3.8"

services:
  hardhat:
    image: node:16
    container_name: hardhat
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "8545:8545"
    command: sh -c "npm install --verbose && npx hardhat node"

  frontend:
    image: node:16
    container_name: frontend
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
    ports:
      - "3000:3000"
    command: sh -c "npm install --verbose && npm start"
    stdin_open: true
